spring:
  pigeon:
    kafka:
      #bootstrap-servers: 192.168.65.3:30092,192.168.65.3:30093,192.168.65.3:30094
      bootstrap-servers: 127.0.0.1:31092,127.0.0.1:31093,127.0.0.1:31094
      consumer:
        group-id: dev-group
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        auto-offset-reset: none
        enable-auto-commit: true
        max-poll-records: 500
        topic: pigeon-dev-events
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        acks: all
        retries: 3
        batch.size: 16384
        linger.ms: 1
        buffer.memory: 33554432
        retry.BackOffPeriod: 2000
        retry.MaxRetryAttempts: 4


  logging:
    level:
      org.springframework.graphql: TRACE
      org.springframework.boot.autoconfigure: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}